'use client';
import { ChangeEvent, FormEvent,useCallback,useEffect,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';
import { ApiError,apiFetch,errorMessage } from '@/lib/api-client';
import { getDictionary,isLocale } from '@/i18n/dictionary';
import type { EventSummary } from '@/types/event';
import { DashboardShell } from '@/components/dashboard/DashboardShell';
import { EventWizard } from '@/components/admin/EventWizard';
import { ThemeEditor } from '@/components/dashboard/ThemeEditor';

type Owner={id:string;displayName:string;email:string;enabled:boolean;createdAt?:string};
type Stats={owners:number;activeOwners:number;events:number;activeEvents:number;media:number;readyMedia:number;wishes:number;storedBytes:number};
type EventItem={event:EventSummary;owner:Owner;mediaCount:number;wishCount:number};
type EventPage={items:EventItem[];page:number;size:number;totalElements:number;totalPages:number};
type ThemeAsset={id:string;url:string;contentType:string;sizeBytes:number;createdAt:string};
type AuditItem={id:string;actorEmail:string;action:string;targetType:string;targetId:string|null;details:string|null;createdAt:string};
type AuditPage={items:AuditItem[];page:number;size:number;totalElements:number;totalPages:number};
type View='overview'|'events'|'owners'|'create'|'assets'|'audit'|'settings';
const emptyAuditPage:AuditPage={items:[],page:0,size:20,totalElements:0,totalPages:0};
const emptyStats:Stats={owners:0,activeOwners:0,events:0,activeEvents:0,media:0,readyMedia:0,wishes:0,storedBytes:0};

export default function AdminPage(){
 const p=useParams<{locale:string}>();const locale=isLocale(p.locale)?p.locale:'en';const d=getDictionary(locale);const router=useRouter();
 const[view,setView]=useState<View>('overview');const[owners,setOwners]=useState<Owner[]>([]);const[events,setEvents]=useState<EventPage>({items:[],page:0,size:10,totalElements:0,totalPages:0});const[assets,setAssets]=useState<ThemeAsset[]>([]);const[stats,setStats]=useState<Stats>(emptyStats);const[auditLog,setAuditLog]=useState<AuditPage>(emptyAuditPage);const[auditLoading,setAuditLoading]=useState(false);const[editing,setEditing]=useState<EventSummary|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=useCallback(async(page=0)=>{setError('');try{const me=await apiFetch<{role:string}>('/auth/me');if(me.role!=='SUPER_ADMIN'){router.replace(`/${locale}/dashboard`);return}const[ownerData,eventData,statData,assetData]=await Promise.all([apiFetch<Owner[]>('/admin/owners'),apiFetch<EventPage>(`/admin/events/page?page=${page}&size=10`),apiFetch<Stats>('/admin/stats'),apiFetch<ThemeAsset[]>('/admin/theme-assets')]);setOwners(ownerData);setEvents(eventData);setStats(statData);setAssets(assetData)}catch(err){if(err instanceof ApiError&&err.status===401)router.replace(`/${locale}/login`);else setError(errorMessage(err,'The admin data could not be loaded.'))}finally{setLoading(false)}},[locale,router]);
 useEffect(()=>{void load()},[load]);
 const loadAudit=useCallback(async(page=0)=>{setAuditLoading(true);setError('');try{const data=await apiFetch<AuditPage>(`/admin/audit-log?page=${page}&size=20`);setAuditLog(data)}catch(err){setError(errorMessage(err,'The audit log could not be loaded.'))}finally{setAuditLoading(false)}},[]);
 useEffect(()=>{if(view==='audit')void loadAudit(0)},[view,loadAudit]);
 async function createOwner(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);setBusy(true);setError('');setNotice('');try{await apiFetch('/admin/owners',{method:'POST',body:JSON.stringify({displayName:fd.get('name'),email:fd.get('email'),password:fd.get('password')})});form.reset();setNotice('Owner account created successfully. Share their email and password so they can sign in.');await load(events.page)}catch(err){setError(errorMessage(err,'The owner account could not be created.'))}finally{setBusy(false)}}
 async function toggleOwner(owner:Owner){setError('');try{const updated=await apiFetch<Owner>(`/admin/owners/${owner.id}/enabled?value=${!owner.enabled}`,{method:'PATCH'});setOwners(current=>current.map(item=>item.id===updated.id?updated:item));setNotice(`${updated.displayName} is now ${updated.enabled?'active':'disabled'}.`);const newStats=await apiFetch<Stats>('/admin/stats');setStats(newStats)}catch(err){setError(errorMessage(err,'The owner status could not be changed.'))}}
 async function uploadAsset(change:ChangeEvent<HTMLInputElement>){const file=change.target.files?.[0];change.target.value='';if(!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);await apiFetch('/admin/theme-assets',{method:'POST',body});const assetData=await apiFetch<ThemeAsset[]>('/admin/theme-assets');setAssets(assetData);setNotice('Background image added to the library.')}catch(err){setError(errorMessage(err,'The image could not be uploaded.'))}finally{setBusy(false)}}
 async function copyAssetUrl(asset:ThemeAsset){await navigator.clipboard.writeText(asset.url);setNotice('Image URL copied to clipboard.')}
 function created(){setNotice('Event published successfully.');void load(0)}
 const navItems:{key:View;label:string;icon:string;badge?:number;primary?:boolean}[]=[
  {key:'overview',label:'Overview',icon:'overview'},
  {key:'events',label:'All events',icon:'events',badge:stats.events},
  {key:'owners',label:'All users',icon:'owners',badge:stats.owners},
  {key:'assets',label:'Theme assets',icon:'assets'},
  {key:'audit',label:'Audit log',icon:'audit'},
  {key:'settings',label:'Settings',icon:'settings'},
  {key:'create',label:'Create event',icon:'plus',primary:true},
 ];
 const nav=<>{navItems.map(item=><button key={item.key} className={`${view===item.key?'active':''} ${item.primary?'nav-primary':''}`} onClick={()=>setView(item.key)}><NavIcon type={item.icon}/><span className="nav-label">{item.label}{typeof item.badge==='number'&&<span className="nav-badge">{item.badge}</span>}</span></button>)}</>;
 return <DashboardShell title="Platform control center" subtitle="Monitor performance, manage clients, and publish event experiences." locale={locale} logoutLabel={d.common.logout} role="SUPER_ADMIN" nav={nav}>{error&&<div className="notice notice--error" role="alert"><strong>Something needs attention</strong><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<div className="notice notice--success"><strong>Completed</strong><span>{notice}</span><button onClick={()=>setNotice('')}>Dismiss</button></div>}{loading?<AdminSkeleton/>:<>{view==='overview'&&<Overview stats={stats} events={events.items.slice(0,5)} onCreate={()=>setView('create')} onViewAll={()=>setView('events')}/>} {view==='events'&&<EventsView data={events} locale={locale} onPage={page=>void load(page)} onEdit={setEditing}/>} {view==='owners'&&<OwnersView owners={owners} busy={busy} onSubmit={createOwner} onToggle={toggleOwner}/>} {view==='create'&&<EventWizard owners={owners} locale={locale} onCreated={created}/>} {view==='assets'&&<AssetsView assets={assets} busy={busy} onUpload={uploadAsset} onCopy={copyAssetUrl}/>} {view==='audit'&&<AuditLogView data={auditLog} loading={auditLoading} onPage={page=>void loadAudit(page)}/>} {view==='settings'&&<SettingsView/>} {editing&&<ThemeEditor event={editing} dictionary={d} onClose={()=>setEditing(null)} onSaved={saved=>{setEditing(null);setEvents(current=>({...current,items:current.items.map(item=>item.event.id===saved.id?{...item,event:saved}:item)}));setNotice('Theme updated successfully.')}}/>}</>}</DashboardShell>
}

function Overview({stats,events,onCreate,onViewAll}:{stats:Stats;events:EventItem[];onCreate:()=>void;onViewAll:()=>void}){return <div className="overview-stack"><section className="welcome-panel"><div><span>BRAVA EVENT OPERATIONS</span><h2>Every event, client, and memory in one place.</h2><p>A real-time view of platform activity and secure media delivery.</p><button className="button button--light" onClick={onCreate}>Create a new event</button></div><div className="welcome-visual"><i/><i/><i/><strong>{stats.activeEvents}<small>Live events</small></strong></div></section><section className="stat-grid"><Stat label="Total events" value={stats.events} detail={`${stats.activeEvents} currently active`} tone="blue"/><Stat label="Client accounts" value={stats.owners} detail={`${stats.activeOwners} enabled`} tone="navy"/><Stat label="Media received" value={stats.media} detail={`${stats.readyMedia} validated and ready`} tone="cyan"/><Stat label="Private wishes" value={stats.wishes} detail={`${formatBytes(stats.storedBytes)} securely stored`} tone="violet"/></section><section className="data-panel"><div className="section-bar"><div><span>RECENT ACTIVITY</span><h3>Latest events</h3></div><button onClick={onViewAll}>View all events</button></div><EventTable items={events}/></section></div>}
function EventsView({data,locale,onPage,onEdit}:{data:EventPage;locale:string;onPage:(page:number)=>void;onEdit:(event:EventSummary)=>void}){return <section className="data-panel"><div className="section-bar"><div><span>EVENT PORTFOLIO</span><h3>All events</h3><p>{data.totalElements} experiences managed through Brava.</p></div></div><EventTable items={data.items} locale={locale} onEdit={onEdit}/><div className="pagination"><span>Page {data.page+1} of {Math.max(1,data.totalPages)}</span><div><button disabled={data.page===0} onClick={()=>onPage(data.page-1)}>Previous</button><button disabled={data.page+1>=data.totalPages} onClick={()=>onPage(data.page+1)}>Next</button></div></div></section>}
function EventTable({items,locale='en',onEdit}:{items:EventItem[];locale?:string;onEdit?:(event:EventSummary)=>void}){if(!items.length)return <div className="professional-empty"><strong>No events yet</strong><span>Create the first Brava event experience to see it here.</span></div>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Event</th><th>Client</th><th>Status</th><th>Activity</th><th>Access expires</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.event.id}><td><strong>{item.event.names}</strong><small>/{item.event.slug}</small></td><td><span>{item.owner.displayName}</span><small>{item.owner.email}</small></td><td><span className={`status-pill ${item.event.active?'status-pill--live':'status-pill--muted'}`}><i/>{item.event.active?'Live':'Inactive'}</span></td><td><span>{item.mediaCount} media</span><small>{item.wishCount} wishes</small></td><td><span>{new Date(item.event.expiresAt).toLocaleDateString()}</span><small>Retention {new Date(item.event.mediaDeleteAt).toLocaleDateString()}</small></td><td><div className="table-actions"><a href={`/${locale}/e/${item.event.slug}`} target="_blank">Public page</a>{onEdit&&<button onClick={()=>onEdit(item.event)}>Edit design</button>}<a href={`/${locale}/login`} target="_blank">Owner login</a></div></td></tr>)}</tbody></table></div>}
function OwnersView({owners,busy,onSubmit,onToggle}:{owners:Owner[];busy:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onToggle:(owner:Owner)=>void}){return <div className="owner-management"><section className="data-panel owner-create-panel"><div className="section-bar"><div><span>CLIENT ONBOARDING</span><h3>Create owner account</h3><p>Give a client an email and password so they can sign in to their own event workspace.</p></div></div><form className="professional-form" onSubmit={onSubmit}><label className="field"><span>Client or company name</span><input name="name" required maxLength={120} placeholder="Client display name"/></label><label className="field"><span>Email address</span><input name="email" type="email" required maxLength={190} placeholder="client@company.com"/></label><label className="field"><span>Password</span><input name="password" type="password" minLength={10} maxLength={72} required placeholder="Minimum 10 characters"/><small>The client signs in with this email and password.</small></label><button className="button button--primary" disabled={busy}>{busy?'Creating secure account…':'Create owner account'}</button></form></section><section className="data-panel"><div className="section-bar"><div><span>CLIENT DIRECTORY</span><h3>Owner accounts</h3><p>{owners.length} total client accounts.</p></div></div><div className="client-list client-list--owners">{owners.map(owner=><article key={owner.id}><span className="client-avatar">{initials(owner.displayName)}</span><div><strong>{owner.displayName}</strong><small>{owner.email}</small></div><span className={`status-pill ${owner.enabled?'status-pill--live':'status-pill--muted'}`}><i/>{owner.enabled?'Active':'Disabled'}</span><div className="table-actions"><button onClick={()=>onToggle(owner)}>{owner.enabled?'Disable':'Enable'}</button></div></article>)}</div></section></div>}
function AssetsView({assets,busy,onUpload,onCopy}:{assets:ThemeAsset[];busy:boolean;onUpload:(e:ChangeEvent<HTMLInputElement>)=>void;onCopy:(asset:ThemeAsset)=>void}){return <section className="data-panel"><div className="section-bar"><div><span>BACKGROUND LIBRARY</span><h3>Theme assets</h3><p>Reusable background images uploaded across every event.</p></div><label className="button button--primary asset-upload-button">{busy?'Uploading…':'Upload image'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={onUpload} disabled={busy}/></label></div>{assets.length===0?<div className="professional-empty"><strong>No background images yet</strong><span>Images you upload here — or from the event wizard — appear in this library.</span></div>:<div className="asset-grid">{assets.map(asset=><figure key={asset.id} className="asset-card"><img src={asset.url} alt=""/><figcaption><small>{formatBytes(asset.sizeBytes)} · {new Date(asset.createdAt).toLocaleDateString()}</small><button onClick={()=>onCopy(asset)}>Copy URL</button></figcaption></figure>)}</div>}</section>}
function AuditLogView({data,loading,onPage}:{data:AuditPage;loading:boolean;onPage:(page:number)=>void}){return <section className="data-panel"><div className="section-bar"><div><span>ACCOUNTABILITY</span><h3>Audit log</h3><p>Who did what, across owner accounts and events.</p></div></div>{loading?<AdminSkeleton/>:data.items.length===0?<div className="professional-empty"><strong>No activity yet</strong><span>Admin actions like creating owners or publishing events will show up here.</span></div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Target</th><th>Details</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><small>{new Date(item.createdAt).toLocaleString()}</small></td><td>{item.actorEmail}</td><td><span className="status-pill status-pill--live"><i/>{item.action.replaceAll('_',' ')}</span></td><td><small>{item.targetType}</small></td><td>{item.details||'—'}</td></tr>)}</tbody></table></div>}<div className="pagination"><span>Page {data.page+1} of {Math.max(1,data.totalPages)}</span><div><button disabled={data.page===0} onClick={()=>onPage(data.page-1)}>Previous</button><button disabled={data.page+1>=data.totalPages} onClick={()=>onPage(data.page+1)}>Next</button></div></div></section>}

function SettingsView(){
 const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');setNotice('');if(next!==confirm){setError('The new passwords do not match.');return}setBusy(true);try{await apiFetch('/auth/me/password',{method:'PUT',body:JSON.stringify({currentPassword:current,newPassword:next})});setCurrent('');setNext('');setConfirm('');setNotice('Password updated successfully.')}catch(err){setError(errorMessage(err,'The password could not be updated.'))}finally{setBusy(false)}}
 return <section className="data-panel"><div className="section-bar"><div><span>ACCOUNT</span><h3>Settings</h3><p>Manage your Super Admin sign-in credentials.</p></div></div><form className="professional-form" onSubmit={submit}><label className="field"><span>Current password</span><input type="password" required value={current} onChange={e=>setCurrent(e.target.value)} autoComplete="current-password"/></label><label className="field"><span>New password</span><input type="password" required minLength={10} maxLength={72} value={next} onChange={e=>setNext(e.target.value)} autoComplete="new-password"/></label><label className="field"><span>Confirm new password</span><input type="password" required minLength={10} maxLength={72} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success">{notice}</p>}<button className="button button--primary" disabled={busy}>{busy?'Saving…':'Update password'}</button></form></section>
}

function Stat({label,value,detail,tone}:{label:string;value:number;detail:string;tone:string}){return <article className={`stat-card stat-card--${tone}`}><div className="stat-icon"><span/></div><p>{label}</p><strong>{value.toLocaleString()}</strong><small>{detail}</small></article>}
function NavIcon({type}:{type:string}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={type==='overview'?'M4 13h6V4H4v9Zm0 7h6v-5H4v5Zm10 0h6v-9h-6v9Zm0-16v5h6V4h-6Z':type==='events'?'M6 3v3m12-3v3M4 9h16M5 5h14a1 1 0 0 1 1 1v14H4V6a1 1 0 0 1 1-1Z':type==='owners'?'M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m7-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 2.13a4 4 0 0 1 0 7.75':type==='assets'?'M4 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5Zm3 12 4.5-6 3 4 2-2.5L19 17H7Z':type==='settings'?'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm8-3a7.9 7.9 0 0 0-.15-1.5l2.1-1.6-2-3.4-2.5 1a8 8 0 0 0-2.6-1.5L14.4 2H9.6l-.45 2.5a8 8 0 0 0-2.6 1.5l-2.5-1-2 3.4 2.1 1.6a8 8 0 0 0 0 3l-2.1 1.6 2 3.4 2.5-1a8 8 0 0 0 2.6 1.5L9.6 22h4.8l.45-2.5a8 8 0 0 0 2.6-1.5l2.5 1 2-3.4-2.1-1.6c.1-.5.15-1 .15-1.5Z':type==='audit'?'M9 2h6l5 5v13a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3Zm5 1.5V8h4.5M9 13h6M9 17h6M9 9h2':'M12 5v14M5 12h14'} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function AdminSkeleton(){return <div className="admin-skeleton"><span/><span/><span/><span/></div>}
function formatBytes(bytes:number){if(bytes<1024*1024)return`${Math.ceil(bytes/1024)} KB`;if(bytes<1024*1024*1024)return`${(bytes/1024/1024).toFixed(1)} MB`;return`${(bytes/1024/1024/1024).toFixed(1)} GB`}
function initials(value:string){return value.split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')}
