'use client';
import { FormEvent,useCallback,useEffect,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';
import { ApiError,apiFetch,errorMessage } from '@/lib/api-client';
import { getDictionary,isLocale } from '@/i18n/dictionary';
import type { EventSummary } from '@/types/event';
import { DashboardShell } from '@/components/dashboard/DashboardShell';
import { EventWizard } from '@/components/admin/EventWizard';
import { ThemeEditor } from '@/components/dashboard/ThemeEditor';

type Owner={id:string;displayName:string;email:string;enabled:boolean;createdAt?:string};
type Stats={owners:number;activeOwners:number;events:number;activeEvents:number;media:number;readyMedia:number;wishes:number;storedBytes:number};
type EventItem={event:EventSummary;owner:Owner;mediaCount:number;wishCount:number};
type EventPage={items:EventItem[];page:number;size:number;totalElements:number;totalPages:number};
type View='overview'|'events'|'owners'|'create';
const emptyStats:Stats={owners:0,activeOwners:0,events:0,activeEvents:0,media:0,readyMedia:0,wishes:0,storedBytes:0};

export default function AdminPage(){
 const p=useParams<{locale:string}>();const locale=isLocale(p.locale)?p.locale:'en';const d=getDictionary(locale);const router=useRouter();
 const[view,setView]=useState<View>('overview');const[owners,setOwners]=useState<Owner[]>([]);const[events,setEvents]=useState<EventPage>({items:[],page:0,size:10,totalElements:0,totalPages:0});const[stats,setStats]=useState<Stats>(emptyStats);const[editing,setEditing]=useState<EventSummary|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=useCallback(async(page=0)=>{setError('');try{const me=await apiFetch<{role:string}>('/auth/me');if(me.role!=='SUPER_ADMIN'){router.replace(`/${locale}/dashboard`);return}const[ownerData,eventData,statData]=await Promise.all([apiFetch<Owner[]>('/admin/owners'),apiFetch<EventPage>(`/admin/events/page?page=${page}&size=10`),apiFetch<Stats>('/admin/stats')]);setOwners(ownerData);setEvents(eventData);setStats(statData)}catch(err){if(err instanceof ApiError&&err.status===401)router.replace(`/${locale}/login`);else setError(errorMessage(err,'The admin data could not be loaded.'))}finally{setLoading(false)}},[locale,router]);
 useEffect(()=>{void load()},[load]);
 async function createOwner(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);setBusy(true);setError('');setNotice('');try{await apiFetch('/admin/owners',{method:'POST',body:JSON.stringify({displayName:fd.get('name'),email:fd.get('email'),password:fd.get('password')})});form.reset();setNotice('Owner account created successfully.');await load(events.page)}catch(err){setError(errorMessage(err,'The owner account could not be created.'))}finally{setBusy(false)}}
 async function toggleOwner(owner:Owner){setError('');try{const updated=await apiFetch<Owner>(`/admin/owners/${owner.id}/enabled?value=${!owner.enabled}`,{method:'PATCH'});setOwners(current=>current.map(item=>item.id===updated.id?updated:item));setNotice(`${updated.displayName} is now ${updated.enabled?'active':'disabled'}.`);const newStats=await apiFetch<Stats>('/admin/stats');setStats(newStats)}catch(err){setError(errorMessage(err,'The owner status could not be changed.'))}}
 function created(){setNotice('Event published successfully.');void load(0)}
 return <DashboardShell title="Platform control center" subtitle="Monitor performance, manage clients, and publish event experiences." locale={locale} logoutLabel={d.common.logout} role="SUPER_ADMIN"><nav className="workspace-nav"><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}><NavIcon type="overview"/>Overview</button><button className={view==='events'?'active':''} onClick={()=>setView('events')}><NavIcon type="events"/>All events <span>{stats.events}</span></button><button className={view==='owners'?'active':''} onClick={()=>setView('owners')}><NavIcon type="owners"/>Clients <span>{stats.owners}</span></button><button className={view==='create'?'active nav-primary':''} onClick={()=>setView('create')}><NavIcon type="plus"/>Create event</button></nav>{error&&<div className="notice notice--error" role="alert"><strong>Something needs attention</strong><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<div className="notice notice--success"><strong>Completed</strong><span>{notice}</span><button onClick={()=>setNotice('')}>Dismiss</button></div>}{loading?<AdminSkeleton/>:<>{view==='overview'&&<Overview stats={stats} events={events.items.slice(0,5)} onCreate={()=>setView('create')} onViewAll={()=>setView('events')}/>} {view==='events'&&<EventsView data={events} locale={locale} onPage={page=>void load(page)} onEdit={setEditing}/>} {view==='owners'&&<OwnersView owners={owners} busy={busy} onSubmit={createOwner} onToggle={toggleOwner}/>} {view==='create'&&<EventWizard owners={owners} locale={locale} onCreated={created}/>} {editing&&<div className="drawer-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setEditing(null)}><aside className="editor-drawer"><button className="drawer-close" onClick={()=>setEditing(null)} aria-label="Close">Close</button><ThemeEditor event={editing} dictionary={d} onSaved={saved=>{setEditing(saved);setEvents(current=>({...current,items:current.items.map(item=>item.event.id===saved.id?{...item,event:saved}:item)}));setNotice('Theme updated successfully.')}}/></aside></div>}</>}</DashboardShell>
}

function Overview({stats,events,onCreate,onViewAll}:{stats:Stats;events:EventItem[];onCreate:()=>void;onViewAll:()=>void}){return <div className="overview-stack"><section className="welcome-panel"><div><span>BRAVA EVENT OPERATIONS</span><h2>Every event, client, and memory in one place.</h2><p>A real-time view of platform activity and secure media delivery.</p><button className="button button--light" onClick={onCreate}>Create a new event</button></div><div className="welcome-visual"><i/><i/><i/><strong>{stats.activeEvents}<small>Live events</small></strong></div></section><section className="stat-grid"><Stat label="Total events" value={stats.events} detail={`${stats.activeEvents} currently active`} tone="blue"/><Stat label="Client accounts" value={stats.owners} detail={`${stats.activeOwners} enabled`} tone="navy"/><Stat label="Media received" value={stats.media} detail={`${stats.readyMedia} validated and ready`} tone="cyan"/><Stat label="Private wishes" value={stats.wishes} detail={`${formatBytes(stats.storedBytes)} securely stored`} tone="violet"/></section><section className="data-panel"><div className="section-bar"><div><span>RECENT ACTIVITY</span><h3>Latest events</h3></div><button onClick={onViewAll}>View all events</button></div><EventTable items={events}/></section></div>}
function EventsView({data,locale,onPage,onEdit}:{data:EventPage;locale:string;onPage:(page:number)=>void;onEdit:(event:EventSummary)=>void}){return <section className="data-panel"><div className="section-bar"><div><span>EVENT PORTFOLIO</span><h3>All events</h3><p>{data.totalElements} experiences managed through Brava.</p></div></div><EventTable items={data.items} locale={locale} onEdit={onEdit}/><div className="pagination"><span>Page {data.page+1} of {Math.max(1,data.totalPages)}</span><div><button disabled={data.page===0} onClick={()=>onPage(data.page-1)}>Previous</button><button disabled={data.page+1>=data.totalPages} onClick={()=>onPage(data.page+1)}>Next</button></div></div></section>}
function EventTable({items,locale='en',onEdit}:{items:EventItem[];locale?:string;onEdit?:(event:EventSummary)=>void}){if(!items.length)return <div className="professional-empty"><strong>No events yet</strong><span>Create the first Brava event experience to see it here.</span></div>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Event</th><th>Client</th><th>Status</th><th>Activity</th><th>Access expires</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.event.id}><td><strong>{item.event.names}</strong><small>/{item.event.slug}</small></td><td><span>{item.owner.displayName}</span><small>{item.owner.email}</small></td><td><span className={`status-pill ${item.event.active?'status-pill--live':'status-pill--muted'}`}><i/>{item.event.active?'Live':'Inactive'}</span></td><td><span>{item.mediaCount} media</span><small>{item.wishCount} wishes</small></td><td><span>{new Date(item.event.expiresAt).toLocaleDateString()}</span><small>Retention {new Date(item.event.mediaDeleteAt).toLocaleDateString()}</small></td><td><div className="table-actions"><a href={`/${locale}/e/${item.event.slug}`} target="_blank">Public page</a>{onEdit&&<button onClick={()=>onEdit(item.event)}>Edit design</button>}</div></td></tr>)}</tbody></table></div>}
function OwnersView({owners,busy,onSubmit,onToggle}:{owners:Owner[];busy:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onToggle:(owner:Owner)=>void}){return <div className="owner-management"><section className="data-panel owner-create-panel"><div className="section-bar"><div><span>CLIENT ONBOARDING</span><h3>Create owner account</h3><p>Give a client secure access to their event workspace.</p></div></div><form className="professional-form" onSubmit={onSubmit}><label className="field"><span>Client or company name</span><input name="name" required maxLength={120} placeholder="Client display name"/></label><label className="field"><span>Email address</span><input name="email" type="email" required maxLength={190} placeholder="client@company.com"/></label><label className="field"><span>Temporary password</span><input name="password" type="password" minLength={10} maxLength={72} required placeholder="Minimum 10 characters"/><small>The owner can use this to sign in immediately.</small></label><button className="button button--primary" disabled={busy}>{busy?'Creating secure account…':'Create owner account'}</button></form></section><section className="data-panel"><div className="section-bar"><div><span>CLIENT DIRECTORY</span><h3>Owner accounts</h3><p>{owners.length} total client accounts.</p></div></div><div className="client-list">{owners.map(owner=><article key={owner.id}><span className="client-avatar">{initials(owner.displayName)}</span><div><strong>{owner.displayName}</strong><small>{owner.email}</small></div><span className={`status-pill ${owner.enabled?'status-pill--live':'status-pill--muted'}`}><i/>{owner.enabled?'Active':'Disabled'}</span><time>{owner.createdAt?new Date(owner.createdAt).toLocaleDateString():'—'}</time><button className="button button--table" onClick={()=>onToggle(owner)}>{owner.enabled?'Disable access':'Enable access'}</button></article>)}</div></section></div>}
function Stat({label,value,detail,tone}:{label:string;value:number;detail:string;tone:string}){return <article className={`stat-card stat-card--${tone}`}><div className="stat-icon"><span/></div><p>{label}</p><strong>{value.toLocaleString()}</strong><small>{detail}</small></article>}
function NavIcon({type}:{type:string}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={type==='overview'?'M4 13h6V4H4v9Zm0 7h6v-5H4v5Zm10 0h6v-9h-6v9Zm0-16v5h6V4h-6Z':type==='events'?'M6 3v3m12-3v3M4 9h16M5 5h14a1 1 0 0 1 1 1v14H4V6a1 1 0 0 1 1-1Z':type==='owners'?'M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m7-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 2.13a4 4 0 0 1 0 7.75':'M12 5v14M5 12h14'} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function AdminSkeleton(){return <div className="admin-skeleton"><span/><span/><span/><span/></div>}
function formatBytes(bytes:number){if(bytes<1024*1024)return`${Math.ceil(bytes/1024)} KB`;if(bytes<1024*1024*1024)return`${(bytes/1024/1024).toFixed(1)} MB`;return`${(bytes/1024/1024/1024).toFixed(1)} GB`}
function initials(value:string){return value.split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')}
